title: Shift Plotter
email: kgoforth1503@gmail.com
description: >-
  Plot shift points for different transmission ratios.
baseurl: "/Shift-Plotter"
url: "https://kforth.github.io/Shift-Plotter"
repo_url: "https://github.com/kForth/Shift-Plotter"
kofi_id: Q5Q01020LV
